name: app_meditation
description: Mobile app for iOS

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  just_audio: ^0.9.31
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.6.1
  intl: ^0.17.0

dev_dependencies:
  dart_code_metrics: ^5.4.0
  flutter_test:
    sdk: flutter
  surf_lint_rules: ^1.0.0

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/audio/
    - assets/images/